apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: eunjitest_image/front
  newTag: prod.4
- name: goodbirdacr.azurecr.io/eunjitest_image/front
  newTag: dev

patches:
- path: patch_deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: eunji-test-front
    version: v1
