apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: nginx
    newTag: dev

patches:
  - path: patch_deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: eunji-test
