apiVersion: apps/v1
kind: Deployment
metadata:
  name: eunji-test
  namespace: eunjitest
spec:
  template:
    spec:
      containers:
      - name: nginx-container
        env:
        - name: env
          value: development

