apiVersion: apps/v1
kind: Deployment
metadata:
  name: eunji-test
spec:
  template:
    spec:
      containers:
      - name: eunjitest-front-container
        # 여기서는 환경 변수를 추가하거나 다른 설정을 변경할 수 있습니다.
        env:
        - name: APP_ENV
          value: development
