apiVersion: apps/v1
kind: Deployment
metadata:
  name: eunji-test
  namespace: eunjitest
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: eunji-test
  template:
    metadata:
      labels:
        app: eunji-test
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
