apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

# images:
# - name: goodbirdacr.azurecr.io/eunjitest_image/front
#   newName: goodbirdacr.azurecr.io/eunjitest_image/front
#   newTag: latest
