apiVersion: v1
kind: Service
metadata:
  name: eunji-test-service
  namespace: eunjitest
spec:
  selector:
    app: eunji-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
